name: Playwright MassMessage & VaultMedia Tests with Allure Reports

on:
  schedule:
    # 4:00 AM IST = 10:30 PM UTC
    - cron: '30 22 * * *'
    
    # 11:30 PM IST = 6:00 PM UTC
    - cron: '0 18 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Clean workspace to avoid stale files (like old faker code)
        run: git clean -fdx

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Create .env.ci file from GitHub Secrets
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env.ci
          echo "CREATOR_EMAIL=${{ secrets.CREATOR_EMAIL }}" >> .env.ci
          echo "CREATOR_PASSWORD=${{ secrets.CREATOR_PASSWORD }}" >> .env.ci
          echo "USER1_EMAIL=${{ secrets.USER1_EMAIL }}" >> .env.ci
          echo "USER1_PASSWORD=${{ secrets.USER1_PASSWORD }}" >> .env.ci
          echo "USER2_EMAIL=${{ secrets.USER2_EMAIL }}" >> .env.ci
          echo "USER2_PASSWORD=${{ secrets.USER2_PASSWORD }}" >> .env.ci
          echo "USER3_EMAIL=${{ secrets.USER3_EMAIL }}" >> .env.ci
          echo "USER3_PASSWORD=${{ secrets.USER3_PASSWORD }}" >> .env.ci

      - name: Run only massMessage and massVaultMedia tests
        run: |
          npm run clean
          npx playwright test tests/massMessage.test.js
          npx playwright test tests/massVaultMedia.test.js
        env:
          CI: true

      - name: Generate Allure Report
        run: |
          mkdir -p allure-report
          npx allure generate test-results/allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Playwright HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: html-report

      - name: List report files
        run: ls -la html-report
